# Generated by Django 2.2.4 on 2019-08-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('pname', models.CharField(max_length=100)),
                ('pdesc', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
